# Generated by Django 4.1.7 on 2023-02-17 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_is_superuser_remove_user_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
