# Generated by Django 4.1.7 on 2023-02-17 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
    ]
