# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0022_alter_movieorder_movie_alter_movieorder_user_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_order",
                to="movies.movie",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="user_order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_movie_order",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
