# Generated by Django 4.1.7 on 2023-02-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0023_alter_movieorder_movie_alter_movieorder_user_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="movie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_order",
                to="movies.movie",
            ),
        ),
    ]
