# Generated by Django 4.1.7 on 2023-02-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0024_alter_movieorder_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_order",
                to="movies.movie",
            ),
            preserve_default=False,
        ),
    ]
